// newElectron/divine-library/src/app/components/Scroller/Scroller.tsx
import { createRef } from 'react';
import './Scroller.css';
import React from 'react';

interface PropType {
    speed: number;
    wait: number;
    children: any;
}

function Scroller(props: PropType) {
    let interval: NodeJS.Timer = null, timeout: NodeJS.Timer = null;
    let direction = true; // True = Scrolling moving left.

    let scrollerRef = createRef<HTMLDivElement>();
    let innerRef = createRef<HTMLDivElement>();

    function enter() {
        interval = setInterval(scroll, props.speed);
    }

    function leave() {
        clear();
        scrollerRef.current.scroll(0, 0);
        direction = true;
    }

    function clear() {
        clearTimeout(timeout);
        timeout = null;

        clearInterval(interval);
        interval = null;
    }

    function scroll() {
        const parent = scrollerRef.current.getBoundingClientRect();
        const child =  innerRef.current.getBoundingClientRect();

        if(parent.width < child.width) {
            scrollerRef.current.scrollBy(direction ? 1 : -1, 0);
            if((!direction && child.left >= parent.left-1) || (direction && child.right <= parent.right+1)) {
                if(timeout == null) {
                    timeout = setTimeout(() => {
                        direction = !direction;
                        timeout = null;
                    }, props.wait);
                }
            }
        }
    }

    return(
        <div className="scroller"
            ref={scrollerRef}
            onMouseEnter={enter}
            onMouseLeave={leave}>
                <div ref={innerRef}>{props.children}</div>
        </div>
    );
}

export default Scroller;

// src/components/base/Scroller.svelte
<script lang="ts">
    export let speed: number, wait: number;

    let interval_id = null, timeout_id = null;
    let direction = true; // True = Scrolling moving left.

    let scroller: HTMLDivElement;
    let inner: HTMLDivElement;

    function enter() {
        interval_id = setInterval(scroll, speed);
    }

    function leave() {
        clear();
        scroller.scroll(0, 0);
    }

    function clear() {
        clearTimeout(timeout_id);
        clearInterval(interval_id);
    }

    function scroll() {
        const parent = scroller.getBoundingClientRect();
        const child =  inner.getBoundingClientRect();

        if(parent.width < child.width) {
            scroller.scrollBy(direction ? 1 : -1, 0);
            if((!direction && child.left >= parent.left-1) || (direction && child.right <= parent.right+1)) {
                if(timeout_id == null) {
                    timeout_id = setTimeout(() => {
                        direction = !direction;
                        timeout_id = null;
                    }, wait);
                }
            }
        }
    }
</script>

<div class="scroller"
    bind:this={scroller}
    on:mouseenter={enter}
    on:mouseleave={leave}>
        <div bind:this={inner}><slot></slot></div>
    </div>

<style>
    .scroller {
        overflow-x: hidden;
    }

    .scroller > div {
        white-space: nowrap;
        width: fit-content;
    }
</style>
